---
title: "Table1"
author: "Samantha Bothwell"
date: "4/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(table1)
```

## R Markdown

```{r}
### Load in dem data 
dem <- read.csv("D:/CU/Spring 2021/FDA/Final Project/BIOS7720_FinalProject/Data/DataProcessed/Demographics.csv")[,-c(1:5,8)]

### Rename columns 
colnames(dem) <- c("Gender", "Race/Ethnicity", "Intended Degree", "College", "BMI", "Parent Income", "Average GPA", 
  "Number of Days with PA Data", "Percentage of Data Missing", "Average Sleep Time", "Average Step Count")

### Multiply percentage missing by 100
dem$`Percentage of Data Missing` <- dem$`Percentage of Data Missing`*100

# Format table
my.render.cont <- function(x) {
    with(stats.apply.rounding(stats.default(x), digits=2), c("",
        "Median [25%, 75%]"=sprintf("%s [%s, %s]", 
        MEDIAN, round(summary(x)[2],2), round(summary(x)[5],2))))
}


table1(~`Gender` + `Race/Ethnicity` + `BMI` + `Parent Income` + `Average GPA` + `Intended Degree` + 
    `Average Step Count` + `Average Sleep Time` | `College`, 
    render.continuous = my.render.cont, data = dem, droplevels = FALSE)

table1(~`Gender` + `Race/Ethnicity` + `BMI` + `Parent Income` + `Average GPA` + `Intended Degree` +  
    `College` + `Average Step Count` + `Average Sleep Time`, 
    render.continuous = my.render.cont, data = dem, droplevels = FALSE)
```
